# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: scrapper.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escrapper.proto\"7\n\x16SiteInformationRequest\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07\x63ountry\x18\x02 \x01(\t\",\n\x17SiteInformationResponse\x12\x11\n\tsite_code\x18\x01 \x01(\t2Y\n\x0fSiteInformation\x12\x46\n\x0fget_information\x12\x17.SiteInformationRequest\x1a\x18.SiteInformationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scrapper_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_SITEINFORMATIONREQUEST']._serialized_start=18
  _globals['_SITEINFORMATIONREQUEST']._serialized_end=73
  _globals['_SITEINFORMATIONRESPONSE']._serialized_start=75
  _globals['_SITEINFORMATIONRESPONSE']._serialized_end=119
  _globals['_SITEINFORMATION']._serialized_start=121
  _globals['_SITEINFORMATION']._serialized_end=210
# @@protoc_insertion_point(module_scope)
